name: Deploy Resume Site

on:
  push:
    branches:
      - main
    paths-ignore:
      - "exports/**"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
